export interface StoryChapterDef {
  id: string;
  title: string;
  origin: string;
  chapter: number;
  unlockLevel: string;
  scenes: { speaker: string; text: string }[];
  reward: { cash?: number; moodlet?: { id: string; label: string; value: number; hours: number } };
}

export const STORY_CHAPTERS: StoryChapterDef[] = [
  // Lagos arc
  {
    id: "lagos-1",
    title: "The Call Home",
    origin: "lagos",
    chapter: 1,
    unlockLevel: "stranger",
    scenes: [
      { speaker: "You", text: "The phone rings at 3 AM. It's Mama." },
      { speaker: "Mama", text: "How is America? Are you eating?" },
      { speaker: "You", text: "I'm fine, Mama. Brooklyn is... big." },
      { speaker: "Mama", text: "Don't forget who you are. Send money when you can." },
      { speaker: "You", text: "I won't forget. I promise." },
    ],
    reward: { cash: 10, moodlet: { id: "called-lagos", label: "Mama's voice", value: 8, hours: 4 } },
  },
  {
    id: "lagos-2",
    title: "The Hustle",
    origin: "lagos",
    chapter: 2,
    unlockLevel: "acquaintance",
    scenes: [
      { speaker: "You", text: "I need to find work. Real work." },
      { speaker: "Marcus", text: "You just got here? Everyone starts at the bottom, my guy." },
      { speaker: "You", text: "In Lagos I was running things. Here I'm invisible." },
      { speaker: "Marcus", text: "Invisible means nobody's watching. That's freedom." },
      { speaker: "You", text: "I never thought of it that way." },
    ],
    reward: { cash: 25 },
  },
  {
    id: "lagos-3",
    title: "Finding Your Spot",
    origin: "lagos",
    chapter: 3,
    unlockLevel: "friend",
    scenes: [
      { speaker: "You", text: "This jollof spot on Flatbush... it tastes like home." },
      { speaker: "Mama Rose", text: "You're Nigerian? I can tell by how you eat." },
      { speaker: "You", text: "Lagos born and raised." },
      { speaker: "Mama Rose", text: "Come back anytime. This is your spot now." },
    ],
    reward: { cash: 15, moodlet: { id: "found-spot", label: "Found your spot", value: 10, hours: 6 } },
  },
  {
    id: "lagos-4",
    title: "The Letter",
    origin: "lagos",
    chapter: 4,
    unlockLevel: "close",
    scenes: [
      { speaker: "You", text: "A letter from my brother. He wants to come too." },
      { speaker: "You", text: "How do I tell him it's not what he thinks?" },
      { speaker: "You", text: "That the streets are cold and the rent is cruel?" },
      { speaker: "You", text: "But also... that I'm starting to find my way." },
    ],
    reward: { cash: 50 },
  },
  {
    id: "lagos-5",
    title: "Making It",
    origin: "lagos",
    chapter: 5,
    unlockLevel: "day-one",
    scenes: [
      { speaker: "Mama", text: "Your father would be proud." },
      { speaker: "You", text: "I'm not done yet, Mama. This is just the beginning." },
      { speaker: "You", text: "Brooklyn didn't make it easy. But it made me better." },
      { speaker: "You", text: "Lagos raised me. Brooklyn is raising me again." },
    ],
    reward: { cash: 100, moodlet: { id: "made-it", label: "Making it", value: 15, hours: 12 } },
  },

  // Kingston arc
  {
    id: "kingston-1",
    title: "The Yard",
    origin: "kingston",
    chapter: 1,
    unlockLevel: "stranger",
    scenes: [
      { speaker: "You", text: "Crown Heights smells like home. Patties and exhaust." },
      { speaker: "Auntie Grace", text: "You from yard? Which part?" },
      { speaker: "You", text: "Kingston. Trench Town side." },
      { speaker: "Auntie Grace", text: "Lawd. Come eat something. You look mawga." },
    ],
    reward: { cash: 10, moodlet: { id: "yard-vibes", label: "Yard vibes", value: 8, hours: 4 } },
  },
  {
    id: "kingston-2",
    title: "The Kitchen",
    origin: "kingston",
    chapter: 2,
    unlockLevel: "acquaintance",
    scenes: [
      { speaker: "You", text: "The restaurant kitchen is hot. Hotter than Kingston in August." },
      { speaker: "Chef", text: "You know how to cook?" },
      { speaker: "You", text: "My grandmother taught me. Ackee and saltfish, oxtail, everything." },
      { speaker: "Chef", text: "Show me what you got." },
    ],
    reward: { cash: 25 },
  },
  {
    id: "kingston-3",
    title: "Reggae Night",
    origin: "kingston",
    chapter: 3,
    unlockLevel: "friend",
    scenes: [
      { speaker: "You", text: "Sound system in Flatbush. Feels like Passa Passa." },
      { speaker: "DJ", text: "Request?" },
      { speaker: "You", text: "Anything Beres Hammond." },
      { speaker: "DJ", text: "Say no more, selector." },
      { speaker: "You", text: "For a moment, I'm back on Orange Street." },
    ],
    reward: { cash: 15, moodlet: { id: "reggae-night", label: "Reggae night", value: 10, hours: 6 } },
  },
  {
    id: "kingston-4",
    title: "Island in Brooklyn",
    origin: "kingston",
    chapter: 4,
    unlockLevel: "close",
    scenes: [
      { speaker: "You", text: "Labor Day Parade on Eastern Parkway." },
      { speaker: "You", text: "The music. The flags. The food." },
      { speaker: "You", text: "All these islands, all in one street." },
      { speaker: "You", text: "Maybe Brooklyn IS an island." },
    ],
    reward: { cash: 50 },
  },
  {
    id: "kingston-5",
    title: "Home Two",
    origin: "kingston",
    chapter: 5,
    unlockLevel: "day-one",
    scenes: [
      { speaker: "Grandma", text: "You nah come back?" },
      { speaker: "You", text: "I am back, Grandma. Every day. In everything I cook." },
      { speaker: "You", text: "Kingston is where I'm from. Brooklyn is where I'm going." },
      { speaker: "You", text: "Two homes. One heart." },
    ],
    reward: { cash: 100, moodlet: { id: "home-two", label: "Two homes, one heart", value: 15, hours: 12 } },
  },

  // Accra arc
  {
    id: "accra-1",
    title: "Mama's Shop",
    origin: "accra",
    chapter: 1,
    unlockLevel: "stranger",
    scenes: [
      { speaker: "You", text: "The shop on Nostrand Avenue. It smells like Makola Market." },
      { speaker: "Auntie Grace", text: "You are Ghanaian? Come, come!" },
      { speaker: "You", text: "From Accra. Osu." },
      { speaker: "Auntie Grace", text: "I knew it. I can see it in your face. Welcome home." },
    ],
    reward: { cash: 10, moodlet: { id: "accra-welcome", label: "Akwaaba", value: 8, hours: 4 } },
  },
  {
    id: "accra-2",
    title: "Sunday Best",
    origin: "accra",
    chapter: 2,
    unlockLevel: "acquaintance",
    scenes: [
      { speaker: "You", text: "The church choir sounds like Hillsong Accra." },
      { speaker: "Brother James", text: "You sing?" },
      { speaker: "You", text: "Only when nobody's listening." },
      { speaker: "Brother James", text: "God is always listening. And He likes what He hears." },
    ],
    reward: { cash: 25 },
  },
  {
    id: "accra-3",
    title: "The Funeral Call",
    origin: "accra",
    chapter: 3,
    unlockLevel: "friend",
    scenes: [
      { speaker: "Mama", text: "Uncle Kwame has passed." },
      { speaker: "You", text: "I... I can't come home for the funeral." },
      { speaker: "Mama", text: "I know. Send what you can for the cloth." },
      { speaker: "You", text: "I'm sorry, Mama. I'm so sorry." },
    ],
    reward: { cash: 15, moodlet: { id: "funeral-call", label: "Missing home", value: -5, hours: 6 } },
  },
  {
    id: "accra-4",
    title: "Market Day",
    origin: "accra",
    chapter: 4,
    unlockLevel: "close",
    scenes: [
      { speaker: "You", text: "Saturday market in Crown Heights." },
      { speaker: "You", text: "Plantain, yam, palm oil. All here." },
      { speaker: "You", text: "The old woman selling kenkey doesn't speak English." },
      { speaker: "You", text: "But when I speak Twi, her whole face lights up." },
    ],
    reward: { cash: 50 },
  },
  {
    id: "accra-5",
    title: "Roots",
    origin: "accra",
    chapter: 5,
    unlockLevel: "day-one",
    scenes: [
      { speaker: "You", text: "They ask me where I'm from." },
      { speaker: "You", text: "I used to say Accra. Then Brooklyn. Now I say both." },
      { speaker: "You", text: "The kente cloth Mama sent hangs on my wall." },
      { speaker: "You", text: "These roots don't break. They just grow longer." },
    ],
    reward: { cash: 100, moodlet: { id: "roots", label: "Deep roots", value: 15, hours: 12 } },
  },
  // Santo Domingo arc
  {
    id: "santo-domingo-1",
    title: "La Llegada",
    origin: "santo-domingo",
    chapter: 1,
    unlockLevel: "stranger",
    scenes: [
      { speaker: "You", text: "Bushwick smells like chimichurris and diesel." },
      { speaker: "Tito", text: "Eh, you just came? From where?" },
      { speaker: "You", text: "Santo Domingo. La capital." },
      { speaker: "Tito", text: "Bienvenido. The bodega is your embassy now." },
    ],
    reward: { cash: 10, moodlet: { id: "la-llegada", label: "Fresh off the plane", value: 8, hours: 4 } },
  },
  {
    id: "santo-domingo-2",
    title: "The Barbershop",
    origin: "santo-domingo",
    chapter: 2,
    unlockLevel: "acquaintance",
    scenes: [
      { speaker: "You", text: "I need a shape-up. Something that looks like home." },
      { speaker: "Barber", text: "Dominicano? Say less. I got you." },
      { speaker: "You", text: "My mother always said a man's hair is his crown." },
      { speaker: "Barber", text: "Your mother is right. Sit down, king." },
    ],
    reward: { cash: 25 },
  },
  {
    id: "santo-domingo-3",
    title: "Dembow Night",
    origin: "santo-domingo",
    chapter: 3,
    unlockLevel: "friend",
    scenes: [
      { speaker: "You", text: "The bass is shaking the floor. Dembow in Brooklyn." },
      { speaker: "DJ", text: "This one goes out to everybody from the island." },
      { speaker: "You", text: "My feet know this rhythm before my brain does." },
      { speaker: "You", text: "For three minutes I'm not in Brooklyn. I'm on the Malecón." },
    ],
    reward: { cash: 15, moodlet: { id: "dembow-night", label: "Dembow in my veins", value: 10, hours: 6 } },
  },
  {
    id: "santo-domingo-4",
    title: "The Wire",
    origin: "santo-domingo",
    chapter: 4,
    unlockLevel: "close",
    scenes: [
      { speaker: "Abuela", text: "Mijo, did you send the money?" },
      { speaker: "You", text: "Sí, Abuela. Every two weeks." },
      { speaker: "Abuela", text: "Your cousin wants to come. Can you help?" },
      { speaker: "You", text: "I'll try. Tell him it's not easy. But it's possible." },
    ],
    reward: { cash: 50 },
  },
  {
    id: "santo-domingo-5",
    title: "Plátano Power",
    origin: "santo-domingo",
    chapter: 5,
    unlockLevel: "day-one",
    scenes: [
      { speaker: "You", text: "They ask where I'm from. I say the Dominican Republic." },
      { speaker: "You", text: "They say: oh, like the Bronx? I say: no. Like the island." },
      { speaker: "You", text: "But Brooklyn raised me the second time." },
      { speaker: "You", text: "I carry both flags. I don't have to choose." },
    ],
    reward: { cash: 100, moodlet: { id: "platano-power", label: "Plátano power", value: 15, hours: 12 } },
  },

  // Dhaka arc
  {
    id: "dhaka-1",
    title: "The Grocery Run",
    origin: "dhaka",
    chapter: 1,
    unlockLevel: "stranger",
    scenes: [
      { speaker: "You", text: "The halal grocery has fish from Dhaka. Hilsa, frozen but real." },
      { speaker: "Shopkeeper", text: "You are Bangladeshi? Which part?" },
      { speaker: "You", text: "Dhaka. Old Dhaka." },
      { speaker: "Shopkeeper", text: "We have everything here. Almost everything." },
    ],
    reward: { cash: 10, moodlet: { id: "dhaka-grocery", label: "Taste of home", value: 8, hours: 4 } },
  },
  {
    id: "dhaka-2",
    title: "The Code",
    origin: "dhaka",
    chapter: 2,
    unlockLevel: "acquaintance",
    scenes: [
      { speaker: "You", text: "The library has free Wi-Fi. That's all I needed." },
      { speaker: "Raj", text: "You code too? What language?" },
      { speaker: "You", text: "I learned Python from YouTube tutorials in Dhaka." },
      { speaker: "Raj", text: "Same. Now I debug for people who went to MIT." },
      { speaker: "You", text: "The internet doesn't care where you're from." },
    ],
    reward: { cash: 25 },
  },
  {
    id: "dhaka-3",
    title: "Friday Prayer",
    origin: "dhaka",
    chapter: 3,
    unlockLevel: "friend",
    scenes: [
      { speaker: "You", text: "The mosque on Church Avenue. Small but full." },
      { speaker: "Imam", text: "Welcome, brother. You are new?" },
      { speaker: "You", text: "New to Brooklyn. Not new to prayer." },
      { speaker: "Imam", text: "Then you are already home." },
    ],
    reward: { cash: 15, moodlet: { id: "friday-prayer", label: "At peace", value: 10, hours: 6 } },
  },
  {
    id: "dhaka-4",
    title: "The Flood Call",
    origin: "dhaka",
    chapter: 4,
    unlockLevel: "close",
    scenes: [
      { speaker: "Amma", text: "The monsoon took the roof. We need help." },
      { speaker: "You", text: "I'm sending money tonight." },
      { speaker: "You", text: "I think about it every day. The water rising." },
      { speaker: "You", text: "Here the buildings stand. Back home, nothing is permanent." },
    ],
    reward: { cash: 50 },
  },
  {
    id: "dhaka-5",
    title: "Two Worlds Online",
    origin: "dhaka",
    chapter: 5,
    unlockLevel: "day-one",
    scenes: [
      { speaker: "You", text: "My sister video-calls from Dhaka. She's learning to code now too." },
      { speaker: "You", text: "I told her: the distance doesn't matter. The Wi-Fi does." },
      { speaker: "You", text: "Dhaka taught me to survive. Brooklyn taught me to build." },
      { speaker: "You", text: "Somewhere between the two, I found my language." },
    ],
    reward: { cash: 100, moodlet: { id: "two-worlds", label: "Two worlds, one signal", value: 15, hours: 12 } },
  },

  // Small-town Ohio arc
  {
    id: "ohio-1",
    title: "The Bus Station",
    origin: "ohio",
    chapter: 1,
    unlockLevel: "stranger",
    scenes: [
      { speaker: "You", text: "Port Authority at midnight. The bus from Columbus took fourteen hours." },
      { speaker: "You", text: "Back home the tallest thing is the water tower." },
      { speaker: "You", text: "Here the buildings don't stop." },
      { speaker: "You", text: "Nobody knows me. That's the point." },
    ],
    reward: { cash: 10, moodlet: { id: "new-arrival", label: "Wide-eyed", value: 8, hours: 4 } },
  },
  {
    id: "ohio-2",
    title: "The Outsider",
    origin: "ohio",
    chapter: 2,
    unlockLevel: "acquaintance",
    scenes: [
      { speaker: "You", text: "Everyone here has a community. A neighborhood. A people." },
      { speaker: "Stranger", text: "Where are you from?" },
      { speaker: "You", text: "Ohio." },
      { speaker: "Stranger", text: "Ohio? What's in Ohio?" },
      { speaker: "You", text: "Nothing. That's why I'm here." },
    ],
    reward: { cash: 25 },
  },
  {
    id: "ohio-3",
    title: "The First Friend",
    origin: "ohio",
    chapter: 3,
    unlockLevel: "friend",
    scenes: [
      { speaker: "You", text: "I met someone who didn't ask where I'm from." },
      { speaker: "You", text: "They asked what I'm about. That's different." },
      { speaker: "You", text: "In Ohio everyone knew my family. My history." },
      { speaker: "You", text: "Here I get to write my own." },
    ],
    reward: { cash: 15, moodlet: { id: "first-friend", label: "Found someone", value: 10, hours: 6 } },
  },
  {
    id: "ohio-4",
    title: "The Call Back",
    origin: "ohio",
    chapter: 4,
    unlockLevel: "close",
    scenes: [
      { speaker: "Mom", text: "Your dad's not doing great. Can you come home for a bit?" },
      { speaker: "You", text: "I... I'll try." },
      { speaker: "You", text: "Home. The word means two things now." },
      { speaker: "You", text: "The place I left and the place I'm building." },
    ],
    reward: { cash: 50 },
  },
  {
    id: "ohio-5",
    title: "Flyover No More",
    origin: "ohio",
    chapter: 5,
    unlockLevel: "day-one",
    scenes: [
      { speaker: "You", text: "Someone at work asked if I miss Ohio." },
      { speaker: "You", text: "I said: I miss the quiet. The stars. The space." },
      { speaker: "You", text: "But I don't miss being invisible." },
      { speaker: "You", text: "Brooklyn didn't give me roots. It gave me a reason to grow them." },
    ],
    reward: { cash: 100, moodlet: { id: "flyover-no-more", label: "Found my place", value: 15, hours: 12 } },
  },

  // BK Native arc
  {
    id: "bk-native-1",
    title: "The Block",
    origin: "bk-native",
    chapter: 1,
    unlockLevel: "stranger",
    scenes: [
      { speaker: "You", text: "Same block. Different Brooklyn." },
      { speaker: "You", text: "The bodega got a juice bar now. Since when?" },
      { speaker: "Miss Pearl", text: "Baby, you look just like your mama." },
      { speaker: "You", text: "I know, Miss Pearl. I know." },
    ],
    reward: { cash: 10, moodlet: { id: "the-block", label: "Block love", value: 8, hours: 4 } },
  },
  {
    id: "bk-native-2",
    title: "The Rent Letter",
    origin: "bk-native",
    chapter: 2,
    unlockLevel: "acquaintance",
    scenes: [
      { speaker: "You", text: "Rent went up again. Mama's apartment is $2,400 now." },
      { speaker: "You", text: "She's been here since '89." },
      { speaker: "You", text: "The new neighbors don't say good morning." },
      { speaker: "You", text: "But this is still our block." },
    ],
    reward: { cash: 25 },
  },
  {
    id: "bk-native-3",
    title: "The Corner Store",
    origin: "bk-native",
    chapter: 3,
    unlockLevel: "friend",
    scenes: [
      { speaker: "You", text: "Mr. Kim's deli closed. Thirty years on that corner." },
      { speaker: "Dre", text: "They're putting a co-working space there." },
      { speaker: "You", text: "Mr. Kim knew my order since I was eight." },
      { speaker: "Dre", text: "Yeah. Some things you can't co-work." },
    ],
    reward: { cash: 15, moodlet: { id: "corner-store", label: "Brooklyn remembers", value: 10, hours: 6 } },
  },
  {
    id: "bk-native-4",
    title: "The Family Meeting",
    origin: "bk-native",
    chapter: 4,
    unlockLevel: "close",
    scenes: [
      { speaker: "Mama", text: "I might have to move to Jersey." },
      { speaker: "You", text: "No. We'll figure it out." },
      { speaker: "You", text: "This block made us. We don't leave." },
      { speaker: "Mama", text: "I love that you fight. You got that from your father." },
    ],
    reward: { cash: 50 },
  },
  {
    id: "bk-native-5",
    title: "Still Here",
    origin: "bk-native",
    chapter: 5,
    unlockLevel: "day-one",
    scenes: [
      { speaker: "You", text: "They wrote an article about the neighborhood. Called it 'up and coming.'" },
      { speaker: "You", text: "We been here. We been up." },
      { speaker: "You", text: "Brooklyn changes. But the people who made it? We stay." },
      { speaker: "You", text: "This isn't nostalgia. This is home." },
    ],
    reward: { cash: 100, moodlet: { id: "still-here", label: "Still here", value: 15, hours: 12 } },
  },
];

export const STORY_CHAPTER_BY_ID: Record<string, StoryChapterDef> = Object.fromEntries(
  STORY_CHAPTERS.map((c) => [c.id, c]),
);

export const STORY_ORIGINS = ["lagos", "kingston", "accra", "santo-domingo", "dhaka", "ohio", "bk-native"] as const;
export type StoryOrigin = (typeof STORY_ORIGINS)[number];
